#!/bin/sh -e

if [ -z "$EDITOR" ]
then
    EDITOR=nano
fi

cd $(dirname $0)/..

DATE=$(date -I)
YEAR=${DATE/-*/}

git checkout -b $DATE
mkdir -p $YEAR
sed "s/YYYY-MM-DD/$DATE/" template.md > $YEAR/$DATE.md
$EDITOR $YEAR/$DATE.md
