name: Check Filenames 

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  check-filenames:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11 
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Check Filenames
        run: python3 ./scripts/verify_filenames.py
